"""
gafs.dynamicaiagent.modelcomponent - Model Component.

Provides model catalogue, deployment management, and AI inference routing.
"""

from .exceptions import (
    ConflictingModelCatalogueEntryException,
    ConflictingModelDeploymentException,
    FullTextAnalyzerNotExistException,
    InvalidAiRequestException,
    InvalidModelCatalogueEntryException,
    InvalidModelCatalogueSearchCriteriaException,
    InvalidModelComponentConfigurationException,
    InvalidModelDeploymentException,
    InvalidModelDeploymentSearchCriteriaException,
    ModelCatalogueEntryNotFoundException,
    ModelCatalogueIndexNotAvailableException,
    ModelComponentConfigurationException,
    ModelComponentConflictException,
    ModelComponentException,
    ModelComponentInitializationException,
    ModelComponentNotInitializedException,
    ModelComponentOperationException,
    ModelComponentResourceNotFoundException,
    ModelComponentValidationException,
    ModelDeploymentNotFoundException,
)
from .i_model_catalogue_service import IModelCatalogueService
from .i_model_component import IModelComponent
from .i_model_service import IModelService
from .model_catalogue_service import ModelCatalogueService
from .model_component import ModelComponent
from .model_service import ModelService
from .models import (
    AiConnectionParameters,
    AiDeploymentType,
    AiOperationStatus,
    AiOperationStatusEnum,
    AiOperationType,
    AiPayload,
    AiProviderType,
    AiRequest,
    AiResponse,
    AiOutput,
    AudioData,
    AudioDataMessagePart,
    ChatCompletionOutput,
    ChatCompletionPayload,
    ContentType,
    DeploymentSecretEdge,
    DeploymentSelectionOptions,
    DeploymentStatus,
    EmbeddingOutput,
    EmbeddingPayload,
    FileData,
    FileMessagePart,
    ImageUrlMessagePart,
    LogicalOperator,
    Message,
    MessagePart,
    ModelCatalogueEntry,
    ModelCatalogueSearchCriteria,
    ModelCatalogueSearchResultEntry,
    ModelComponentConfigurations,
    ModelDeployment,
    ModelDeploymentEdge,
    ModelDeploymentSearchCriteria,
    ModelStatus,
    RefusalMessagePart,
    Role,
    TagsSearchCriteria,
    TextCompletionOutput,
    TextCompletionPayload,
    TextMessagePart,
    VectorSearchCriteria,
)

__all__ = [
    # Exceptions
    "ConflictingModelCatalogueEntryException",
    "ConflictingModelDeploymentException",
    "FullTextAnalyzerNotExistException",
    "InvalidAiRequestException",
    "InvalidModelCatalogueEntryException",
    "InvalidModelCatalogueSearchCriteriaException",
    "InvalidModelComponentConfigurationException",
    "InvalidModelDeploymentException",
    "InvalidModelDeploymentSearchCriteriaException",
    "ModelCatalogueEntryNotFoundException",
    "ModelCatalogueIndexNotAvailableException",
    "ModelComponentConfigurationException",
    "ModelComponentConflictException",
    "ModelComponentException",
    "ModelComponentInitializationException",
    "ModelComponentNotInitializedException",
    "ModelComponentOperationException",
    "ModelComponentResourceNotFoundException",
    "ModelComponentValidationException",
    "ModelDeploymentNotFoundException",
    # Interfaces
    "IModelCatalogueService",
    "IModelComponent",
    "IModelService",
    # Implementations
    "ModelCatalogueService",
    "ModelComponent",
    "ModelService",
    # AI operation models
    "AiConnectionParameters",
    "AiDeploymentType",
    "AiOperationStatus",
    "AiOperationStatusEnum",
    "AiOperationType",
    "AiPayload",
    "AiProviderType",
    "AiRequest",
    "AiResponse",
    "AiOutput",
    "AudioData",
    "AudioDataMessagePart",
    "ChatCompletionOutput",
    "ChatCompletionPayload",
    "ContentType",
    "EmbeddingOutput",
    "EmbeddingPayload",
    "FileData",
    "FileMessagePart",
    "ImageUrlMessagePart",
    "Message",
    "MessagePart",
    "RefusalMessagePart",
    "Role",
    "TextCompletionOutput",
    "TextCompletionPayload",
    "TextMessagePart",
    # Catalogue / deployment models
    "DeploymentSecretEdge",
    "DeploymentSelectionOptions",
    "DeploymentStatus",
    "LogicalOperator",
    "ModelCatalogueEntry",
    "ModelCatalogueSearchCriteria",
    "ModelCatalogueSearchResultEntry",
    "ModelComponentConfigurations",
    "ModelDeployment",
    "ModelDeploymentEdge",
    "ModelDeploymentSearchCriteria",
    "ModelStatus",
    "TagsSearchCriteria",
    "VectorSearchCriteria",
]
