"""gafs.dynamicaiagent.toolcomponent.exceptions - Tool Component exception classes."""

from .tool_component_exception import ToolComponentException
from .tool_component_exceptions import (
    ToolComponentConfigurationException,
    ToolComponentInitializationException,
    ToolComponentNotInitializedException,
    InvalidToolComponentConfigurationException,
    ToolComponentValidationException,
    InvalidToolCatalogueEntryException,
    InvalidToolCatalogueSearchCriteriaException,
    InvalidToolVersionEntryException,
    InvalidToolVersionSearchCriteriaException,
    InvalidSandboxCatalogueEntryException,
    InvalidSandboxCatalogueSearchCriteriaException,
    InvalidToolInvocationException,
    ToolComponentConflictException,
    ConflictingToolCatalogueEntryException,
    ConflictingToolVersionEntryException,
    ConflictingSandboxCatalogueEntryException,
    ToolComponentResourceNotFoundException,
    ToolCatalogueEntryNotFoundException,
    ToolVersionEntryNotFoundException,
    SandboxCatalogueEntryNotFoundException,
    ToolComponentOperationException,
    ToolCatalogueIndexNotAvailableException,
    FullTextAnalyzerNotExistException,
)

__all__ = [
    "ToolComponentException",
    "ToolComponentConfigurationException",
    "ToolComponentInitializationException",
    "ToolComponentNotInitializedException",
    "InvalidToolComponentConfigurationException",
    "ToolComponentValidationException",
    "InvalidToolCatalogueEntryException",
    "InvalidToolCatalogueSearchCriteriaException",
    "InvalidToolVersionEntryException",
    "InvalidToolVersionSearchCriteriaException",
    "InvalidSandboxCatalogueEntryException",
    "InvalidSandboxCatalogueSearchCriteriaException",
    "InvalidToolInvocationException",
    "ToolComponentConflictException",
    "ConflictingToolCatalogueEntryException",
    "ConflictingToolVersionEntryException",
    "ConflictingSandboxCatalogueEntryException",
    "ToolComponentResourceNotFoundException",
    "ToolCatalogueEntryNotFoundException",
    "ToolVersionEntryNotFoundException",
    "SandboxCatalogueEntryNotFoundException",
    "ToolComponentOperationException",
    "ToolCatalogueIndexNotAvailableException",
    "FullTextAnalyzerNotExistException",
]
